WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = XEPDB1;

DECLARE
   v_user_count NUMBER;
BEGIN
   SELECT COUNT(*)
   INTO v_user_count
   FROM dba_users
   WHERE username = 'TELCO';

   IF v_user_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE USER TELCO IDENTIFIED BY Telco12345 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
   ELSE
      EXECUTE IMMEDIATE 'ALTER USER TELCO IDENTIFIED BY Telco12345 ACCOUNT UNLOCK';
      EXECUTE IMMEDIATE 'ALTER USER TELCO QUOTA UNLIMITED ON USERS';
   END IF;
END;
/

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO TELCO;

CONNECT TELCO/Telco12345@//localhost:1521/XEPDB1

@/workspace/TABLE_CREATION_SCRIPTS.sql

EXIT
