OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/workspace/CUSTOMERS.csv'
INSERT
INTO TABLE customers
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(
   customer_id INTEGER EXTERNAL,
   name        CHAR(100),
   city        CHAR(100),
   signup_date DATE "DD/MM/YYYY",
   tariff_id   INTEGER EXTERNAL
)
