OPTIONS (SKIP=1)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE '/workspace/TARIFFS.csv'
INSERT
INTO TABLE tariffs
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(
   tariff_id    INTEGER EXTERNAL,
   name         CHAR(100),
   monthly_fee  DECIMAL EXTERNAL,
   data_limit   DECIMAL EXTERNAL,
   minute_limit INTEGER EXTERNAL,
   sms_limit    INTEGER EXTERNAL
)
